# Generated by Django 5.2.3 on 2025-07-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.CharField(blank=True, max_length=255, verbose_name="Tags"),
        ),
    ]
