# Generated by Django 5.2.3 on 2025-07-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(
                upload_to="media_library/", verbose_name="Media File"
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="license_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cc0", "CC0"),
                    ("cc-by", "CC BY"),
                    ("cc-by-sa", "CC BY-SA"),
                    ("cc-by-nc", "CC BY-NC"),
                    ("cc-by-nc-sa", "CC BY-NC-SA"),
                    ("cc-by-nd", "CC BY-ND"),
                    ("cc-by-nc-nd", "CC BY-NC-ND"),
                ],
                max_length=50,
                null=True,
                verbose_name="License Type",
            ),
        ),
    ]
